# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/KalmanPaper',
                'doc_host': 'https://SuzuSys.github.io',
                'git_url': 'https://github.com/SuzuSys/KalmanPaper',
                'lib_path': 'KalmanPaper'},
  'syms': { 'KalmanPaper.core': { 'KalmanPaper.core.lam': ('funcs.html#lam', 'KalmanPaper/core.py'),
                                  'KalmanPaper.core.losi': ('funcs.html#losi', 'KalmanPaper/core.py')}}}
