"""ipynb template"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_template.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_template.ipynb 3
import numpy as np
import numpy.typing as npt

# %% ../nbs/00_template.ipynb 4
def foo(a,  # $a$
        b=2 # $b$
        ) -> int: # $c$
  return a**b
