# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/EKF/00_EKF.ipynb.

# %% auto 0
__all__ = ['dxlosi']

# %% ../nbs/EKF/00_EKF.ipynb 13
import numpy as np
import numpy.typing as npt
from .simple import losi

# %% ../nbs/EKF/00_EKF.ipynb 15
def dxlosi(
    x: npt.NDArray[np.float64] # $x$
) -> npt.NDArray[np.float64]: # $\lambda(x)$
  return losi(x) * (1 - losi(x))
