"""Test"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Exp/00_Exp.ipynb.

# %% auto 0
__all__ = ['exper']

# %% ../nbs/Exp/00_Exp.ipynb 3
import numpy as np
import jax.numpy as jnp
import jax.random as jrd
import jax
from jaxtyping import Float, Int, Array, PRNGKeyArray
from . import gen, EKF, VA
from matplotlib import pyplot as plt
from typing import Tuple
from functools import partial

# %% ../nbs/Exp/00_Exp.ipynb 4
@partial(jax.jit, static_argnames=['N', 'T'])
def exper(
    key: PRNGKeyArray,
    N: int,
    T: int,
    G: Float[Array, "{N} {N}"],
    w0: Float[Array, "{N}"],
    Sigma: Float[Array, "{N} {N}"],
    P0: Float[Array, "{N} {N}"], 
    propy1: Float
):
  key_w, key_xy = jrd.split(key, 2)
  W = gen.gen_w(key_w, N, T, G, w0)
  X, Y = gen.gen_xy(key_xy, N, T, Sigma, W, propy1)
  Wtt_EKF, Ptt_EKF = EKF.EKF(N, T, X, Y, G, w0, P0)
  Wtt_VA, Ptt_VA, Xit_VA = VA.VApre(N, T, X, Y, G, w0, P0)
  # W_norm = jnp.sqrt(jnp.sum(W**2, axis=1))
  # RMS_Wtt_EKF = jnp.sqrt(jnp.sum((W - Wtt_EKF)**2, axis=1)) # shape: (T:)
  # RMS_Wtt_VA = jnp.sqrt(jnp.sum((W - Wtt_VA)**2, axis=1))
  
  return X, Y, W, (Wtt_EKF, Ptt_EKF), (Wtt_VA, Ptt_VA, Xit_VA)
