"""simple functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_funcs.ipynb.

# %% auto 0
__all__ = ['losi', 'lam']

# %% ../nbs/01_funcs.ipynb 3
import jax.numpy as jnp
from jaxtyping import Array, Float

# %% ../nbs/01_funcs.ipynb 5
def losi(
    x: Float[Array, ""] # $x$
) -> Float[Array, ""]: # $\sigma(x)=1/(1+ e\\^{-x})$
  return 1/(1+jnp.exp(-x))

# %% ../nbs/01_funcs.ipynb 7
def lam(
    x: Float[Array, ""] # $x$
) -> Float[Array, ""]: # $\lambda(x)$
  return (losi(x) - 0.5)/(2*x)
