"""変分近似"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/VA/00_VA.ipynb.

# %% auto 0
__all__ = ['Ptt', 'wtt', 'xit', 'VApre', 'VAEM']

# %% ../nbs/VA/00_VA.ipynb 3
import jax.numpy as jnp
import jax.lax as lax
import jax.scipy.linalg as jsl
import jax
from jaxtyping import Array, Float, Int
from . import simple as sp
from typing import Tuple
from functools import partial

# %% ../nbs/VA/00_VA.ipynb 5
@jax.jit
def Ptt(
    Ptm:  Float[Array, "N N"], # $\mathbf P_{t/t-1}$
    x:    Float[Array, "N"], # $\mathbf x_t$
    xi:   Float[Array, ""], # $\xi_t$
) -> Float[Array, "N N"]: # $\mathbf P_{t/t}$
  dsigma = 2*sp.lam(xi)
  Ptmx = Ptm @ x
  return Ptm - (dsigma / (1 + dsigma * (x @ Ptmx))) * jnp.outer(Ptmx, Ptmx)

# %% ../nbs/VA/00_VA.ipynb 7
@jax.jit
def wtt(
    Ptm: Float[Array, "N N"],  # $\mathbf P_{t/t-1}$
    Ptt_: Float[Array, "N N"], # $\mathbf P_{t/t}$
    w: Float[Array, "N"],      # $\hat{\mathbf w}_{t/t-1}$
    x: Float[Array, "N"],      # $\mathbf x_t$
    y: Float[Array, ""],      # $y_t$
) -> Float[Array, "N"]:        # $\hat{\mathbf w}_{t/t}$
  return Ptt_ @ (jsl.cho_solve(jsl.cho_factor(Ptm), w) + (y - 1/2) * x)

# %% ../nbs/VA/00_VA.ipynb 9
@jax.jit
def xit(
    Ptm: Float[Array, "N N"], # $\mathbf P_{t/t-1}$
    w: Float[Array, "N"],   # $\hat{\mathbf w}_{t/t-1}$
    x: Float[Array, "N"],   # $\mathbf x_t$
) -> Float[Array, ""]: # $\xi_t$
  return jnp.sqrt(x @ (Ptm + jnp.outer(w,w)) @ x)

# %% ../nbs/VA/00_VA.ipynb 11
@partial(jax.jit, static_argnames=['N', 'T'])
def VApre(
    N: int, # $N$
    T: int, # $T$
    x: Float[Array, "{T} {N}"], # $\{ \mathbf x_t \}_{t=0,\ldots,T-1}$
    y: Float[Array, "{T} {N}"], # $\{ y_t \}_{t=0,\ldots,T-1}$
    G: Float[Array, "{N} {N}"], # $\boldsymbol\Gamma$
    w0: Float[Array, "{N}"], # $\hat{\mathbf w}_{0/-1}$
    P0: Float[Array, "{N} {N}"], # $\mathbf P_{0/-1}$
) -> Tuple[Float[Array, "{T} {N}"], Float[Array, "{T} {N} {N}"], Float[Array, "{T}"]]: # $\{\hat{\mathbf w}_{t/t}\}_{t=0,\ldots,T-1},\{\mathbf P_{t/t}\}_{t=0,\ldots,T-1},\{\xi_t\}_{t=0,\ldots,T-1}$
    def step(carry, inputs):
        Ptm, wtm = carry
        xt, yt = inputs
        xit_ = xit(Ptm, wtm, xt)
        Ptt_ = Ptt(Ptm, xt, xit_)
        wtt_ = wtt(Ptm, Ptt_, wtm, xt, yt)
        return (Ptt_ + G, wtt_), (wtt_, Ptt_, xit_)
    
    _, (W, P, Xi) = lax.scan(
        step,
        (P0, w0),
        (x, y),
        length=T
    )
    return W, P, Xi

# %% ../nbs/VA/00_VA.ipynb 12
@partial(jax.jit, static_argnames=['N', 'T'])
def VAEM(
    N: int, # $N$
    T: int, # $T$
    x: Float[Array, "{T} {N}"], # $\{ \mathbf x_t \}_{t=0,\ldots,T-1}$
    y: Float[Array, "{T} {N}"], # $\{ y_t \}_{t=0,\ldots,T-1}$
    G: Float[Array, "{N} {N}"], # $\boldsymbol\Gamma$
    w0: Float[Array, "{N}"], # $\hat{\mathbf w}_{0/-1}$
    P0: Float[Array, "{N} {N}"], # $\mathbf P_{0/-1}$
    epsilon: Float,
) -> Tuple[Float[Array, "{T} {N}"], Float[Array, "{T} {N} {N}"], Float[Array, "{T}"]]: # $\{\hat{\mathbf w}_{t/t}\}_{t=0,\ldots,T-1},\{\mathbf P_{t/t}\}_{t=0,\ldots,T-1},\{\xi_t\}_{t=0,\ldots,T-1}$
    def inner_iter(state):
        xit_, Ptt_, wtt_, Ptm, wtm, xt, yt, i = state
        xit_af = xit(Ptt_, wtt_, xt)
        Ptt_new = Ptt(Ptm, xt, xit_af)
        wtt_new = wtt(Ptm, Ptt_new, wtm, xt, yt)
        return (xit_af, Ptt_new, wtt_new, Ptm, wtm, xt, yt, i+1)

    def cond_fun(state):
        xit_, Ptt_, wtt_, Ptm, wtm, xt, yt, i = state
        xit_af = xit(Ptt_, wtt_, xt)
        return jnp.logical_and(
            jnp.abs(xit_ - xit_af) >= epsilon,
            i < 100
        )

    def step(carry, inputs):
        Ptm, wtm = carry
        xt, yt = inputs
        xit_ = xit(Ptm, wtm, xt)
        Ptt_ = Ptt(Ptm, xt, xit_)
        wtt_ = wtt(Ptm, Ptt_, wtm, xt, yt)

        init_state = (xit_, Ptt_, wtt_, Ptm, wtm, xt, yt, 0)
        xit_final, Ptt_final, wtt_final, *_ = lax.while_loop(cond_fun, inner_iter, init_state)

        return (Ptt_final + G, wtt_final), (wtt_final, Ptt_final, xit_final)

    _, (W, P, Xi) = lax.scan(step, (P0, w0), (x, y), length=T)
    return W, P, Xi
