project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/SuzuSys/KalmanPaper"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
